[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
run_election = "2E9AkSqVbakqo67j2PjBD27TPZt186EkAoNVghN5mhNM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/devil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"