[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
election = "GzPfcvPz81cigZDy9M6w3vrL5iHbP67VkqVVNb1xGbrY"
token = "9Hg5X6Tb9KrSx9sMzkeU32tzUyXbC5j9Yqx3TF4Eti4w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/devil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"