[features]
seeds = false
skip-lint = false

[programs.localnet]
election = "GzPfcvPz81cigZDy9M6w3vrL5iHbP67VkqVVNb1xGbrY"
token = "9Hg5X6Tb9KrSx9sMzkeU32tzUyXbC5j9Yqx3TF4Eti4w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -r ts-node/register -t 1000000 tests/**/*.ts"
transfer = "yarn transfer"
# test = "yarn mocha -r ts-node/register -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./meta_program.so"

